services:
  app:
    build: .
    volumes:
      - ./app/:/home/local/
    ports:
      - 8888:8888
      - 9005:9005
    stdin_open: true
    tty: true
    # command: >
    #   sh -c '
    #     flutter pub get &&
    #     flutter run -d web-server --web-port=8888 --web-hostname=0.0.0.0
    #   '
